export const SUBMIT_FEEDBACK = 'SUBMIT_FEEDBACK';
export const SUBMIT_FEEDBACK_SUCCESS = 'SUBMIT_FEEDBACK_SUCCESS';
export const SUBMIT_FEEDBACK_FAILURE = 'SUBMIT_FEEDBACK_FAILURE';
export const RESET_ATTENDANCE_FORM = 'RESET_ATTENDANCE_FORM'

export const QUERYING_ATTENDANCE = 'QUERYING_ATTENDANCE';
export const QUERY_ATTENDANCE_SUCCESS = 'QUERY_ATTENDANCE_SUCCESS';
export const QUERY_ATTENDANCE_FAILURE = 'QUERY_ATTENDANCE_FAILURE';
export const RESET_QUERY_FORM = 'RESET_QUERY_FORM';
